services:
  simba:
      command: bash -c "cd src/ && uvicorn --host 0.0.0.0 main:app"
      tty: true
      working_dir: /app
      restart: "always"
      image: convai:latest
      ports:
        - "${PORT-8080:8000}"
      environment:
        - MILVUS_PORT=${MILVUS_PORT}
        - TOP_K=${TOP_K}
        - HEALTH_NPROBE=${HEALTH_NPROBE}
version: "2.3"
