services:
  vector:
      command: bash -c "cd src/ && uvicorn --host 0.0.0.0 main:app"
      tty: true
      working_dir: /app
      restart: "always"
      image: convai:latest
      ports:
        - "${PORT-8080:8000}"
      environment:
        - TEST=${TEST}
version: "2.3"
